### ISSUE TITLE
Incorrect Instagram username

### ISSUE THREAD

**Issue by anujpuri72** [thepushkarp/thepushkarp#1]
**Describe the bug**
Wrong Instagram Username

**To Reproduce**
1. Go to readme.md
2. Click on preview
3. Hower/Click on Instagram badge
4. Open the link
5. See "Username Not found page"

**Expected behaviour**
It should redirect to pushkarp instead of pushkarp.art

**Screenshots**
![bug](https://user-images.githubusercontent.com/42184782/147674687-0011da9d-525d-43d9-bd50-c6e3207d7d52.png)
![bug-2](https://user-images.githubusercontent.com/42184782/147674692-f52da452-a374-4f43-94f6-6e1d27201929.png)

**Comment by thepushkarp** [comment]
Thanks for pointing it out, @anujpuri72. This issue has been resolved with the latest commit.
